### PR TITLE
Com groups

### PR DESCRIPTION
**Pull request by trisketz**

### CODE REVIEW

**Comment by trisketz** [comment]
Food for thought about icons: [](https://www.viget.com/articles/testing-accordion-menu-designs-iconography/?ref=hackingui)

**Comment by mdlama** [comment]
Hi, Jenny.  I'm beginning to think we should just push the code that makes the menu collapsible and not rush through the loading of pages via AJAX.  One thing I noticed on the branch is publication macro cards don't quite work when loaded via AJAX, which I think might be due to the JS not loading properly.  Also, we would need to address breadcrumbs again.  Regardless of the possible coding headaches, in terms of user experience, I think users are used to page reloads when they go to a different page anyways.  I'm thinking of the experience of being scrolled down the page, clicking a new page, only to have it load via AJAX and having to scroll to the top to get to the beginning of the page.  This could be even worse if a user clicks a plugin.  What do you think?

**Comment by mdlama** [comment]
Forgot to mention:  cool article on icons.  Good to bring to the Monday meeting for a discussion.

**Comment by trisketz** [comment]
True, any js code for any macro will need the file to be reinitialized if we are loading pages in via ajax. So that is a good point. As far as the breadcrumbs go, I checked what we were doing on production and it is functioning the same. 

I still think using ajax is an overall better user experience. It's faster since you don't have to reload the dom every time. I understand the problem with scrolling down the menu to have to scroll back up once the page loads however. That being said, it doesn't have to be used everywhere.

**Comment by mdlama** [comment]
How about we continue this discussion on Monday, but go ahead and strip out the ajax group page loading from the collapsible menu code?  For BIOME (and Carrie), the most important and timely thing is the collapsible menu.

**Comment by trisketz** [comment]
Hey Drew, 

I went ahead and removed the ajax from the code. Should be good to go now.

**Pull request merged**
