### PR TITLE
Added com_groups as subtree

### PR DESCRIPTION
**Pull request by trisketz**
I hope I did this right.

### CODE REVIEW

**Comment by mdlama** [comment]
Will take a look.  So far it looks good!!  Did you already make menu changes??

**Comment by trisketz** [comment]
I haven't yet. I wanted to make sure this was the right path first, haha.

**Comment by mdlama** [comment]
Oops!  Just noticed that all of the files are in `app/app/components/com_groups`!!  You want to scratch this pull request and try again?  Best to start over on this one.  I am more than happy to do it as well, but want to give you the chance to get it down.

**Comment by trisketz** [comment]
Ok, let me give it another go.

**Pull request closed without merging**
