### PR TITLE
Site accessibility

### PR DESCRIPTION
**Pull request by trisketz**

### CODE REVIEW

**Comment by mdlama** [comment]
Hi, Jenny.  I think I'm going to have to cherry-pick the commits from this pull request as there were A TON of code changes.  Would you say that your work is really just the first three and last three commits in this pull request?

**Comment by trisketz** [comment]
Yes, the merge branch 'master' to into site_accessibility was me trying to update my branch. But all the work is first 3 and last 3.

**Comment by mdlama** [comment]
Okay, so I checked it out and noticed something with the showcase modules.  Since the white has transparency (0.85), [the green text on the white background](https://contrast-ratio.com/#hsl%2889%2C%2046%25%2C%2034%25%2C%201.0%29-on-hsla%28200%2C100%25%2C100%25%2C0.85%29) can actually fail accessibility standards (even though Chrome gives it a 4.67 independent of opacity).  Any ideas how to address this?  Only thing I can think of is to just remove transparency.

**Comment by trisketz** [comment]
Easiest is to remove the transparency or not have the titles the same color
as links. But I think that might defeat the purpose.

**Comment by mdlama** [comment]
Let’s remove transparency.

**Comment by trisketz** [comment]
I went ahead and removed the transparency, committed, and pushed.

- Updated mixins.scss to remove transparency
- Recompiled the landing pages.

**Comment by mdlama** [comment]
Awesome, thanks, Jenny.  Just beginning to realize how these changes might trickle throughout all the extensions!  Can you explore how links look in group plugins?  As an example, this is what a form post looks like.  Not sure if we want the links underlined in the list views (similar to your previous comment).
Screen Shot 2019-05-28 at 1 43 39 PM

**Comment by trisketz** [comment]
I went through some of the group plugins. I don't think we have an override for the blogs plugin for groups.

There is some issues with the ckEditor css coming up with the underline. I'm not sure how to address this since we do not have an override for this (I believe). There is also an issue with some of the jquery-ui elements getting an underline too (calendar). 

Places I removed the underline:
 - Forums
 - Collections
 - Aside menu
 - Members
 - Default Overview page

Places that need it:
 - CKEditor - css is in the core I believe
 - Blogs - I don't think we have an override
 - Calendar - maybe do an override in another file? Go into jquery-ui.css?
 
Projects I'm unsure on. For some reason, it won't let me get beyond the setup right now. I'll keep playing with it.

**Comment by trisketz** [comment]
I've been giving this a lot of thought. And I feel like I made this harder than it needed to be. I want to cancel this pull request and start over. What do you think?

**Comment by mdlama** [comment]
I think you know better than I whether that is a good idea. :)  So I say go for it - close and restart!

**Pull request closed without merging**
